### PR TITLE
AAE-2026 add @ConditionalOnMissingBean annotation in order to overrid…

### PR DESCRIPTION
**Pull request by jesty**
add @ConditionalOnMissingBean annotation in order to override the bean in Query Service, merged with Notification, Audit

### CODE REVIEW

**Review by zoltanpalfi — APPROVED** [review]
lgtm

**Review by zoltanpalfi — CHANGES_REQUESTED** [review]
Can you open a separate PR @robfrank for your changes and don't use an already approved one please?

**Comment by robfrank** [comment]
@zoltanpalfi  without that fix, the build was red. How to manage it in a better way, if any?

**Comment by zoltanpalfi** [comment]
> @zoltanpalfi without that fix, the build was red. How to manage it in a better way, if any?

In general, you should separate concerns. Thus, you won't have a PR (and then a git comment) saying you add @ContidionalOnMissing annotation in the code while it's actually also changes the parent reference, the module ordering in the pom and so on.

One solution is to have it as a separate pull request those changes. Another solution would be to change this PR description & final commit message to reflect actual changes. Or another one, you can just have someone else to approve it... 😛

**Review by zoltanpalfi — APPROVED** [review]

**Pull request merged**
