### PR TITLE
[AAE-10563]: Fix Identity Service extension 

### PR DESCRIPTION
**Pull request by scaccia**

### CODE REVIEW

**Review by jesty — CHANGES_REQUESTED** [review]
Please check if alfresco-process repo works with those changes.

**Comment by scaccia** [comment]
@jesty The tests, using this new configuration, work correctly on  alfresco-process.
The only two classes that use the interface `IdentityService` are `EmailUserDetailsService` and `FindCandidateAssigneesFunction`. These classes will keep working like before.
Maybe we should refactor KeycloakManagementService because it implements methods used only internally to service

**Comment by scaccia** [comment]
@jesty The tests, using this new configuration, work correctly on  alfresco-process.
The only two classes that use the interface `IdentityService` are `EmailUserDetailsService` and `FindCandidateAssigneesFunction`. These classes will keep working like before.
Maybe we should refactor KeycloakManagementService because it implements

**Review by jesty — APPROVED** [review]
LGTM

**Review by miguelruizdev — APPROVED** [review]

**Pull request merged**
