### PR TITLE
feat(runtime-bundle): provide the process definition name to sub processes

### PR DESCRIPTION
**Pull request by knowings**
This little PR to ensure processes (or sub processes) got their process definition name set once started.

We've noticed it may be absent from events dispatched through RabbitMQ

### CODE REVIEW

**Review by erdemedeiros — CHANGES_REQUESTED** [review]
Hi @knowings,

Thank you for taking the time to investigate the issue and propose a fix for it.

However, I think the problem should be fixed closer to the base event used to create `CloudProcessStartedEvent`, directly in [Activiti core](https://github.com/Activiti/Activiti).


From what I see, the root problem is that this information is not set in [ExecutionEntityManagerImpl.createSubprocessInstance()](https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java#L300)

This test should reproduce the issue:

```java

    private static final String PARENT_PROCESS_CALL_ACTIVITY = "parentproc-843144bc-3797-40db-8edc-d23190b118e3";
    private static final String SUB_PROCESS_CALL_ACTIVITY = "subprocess-fb5f2386-709a-4947-9aa0-bbf31497384f";

    @Test
    public void startProcessEvent_should_includeDefinitionMetadataForChildProcesses() {
        //given
        ProcessDefinition parentProcessDefinition = processRuntime.processDefinition(PARENT_PROCESS_CALL_ACTIVITY);
        ProcessDefinition childProcessDefinition = processRuntime.processDefinition(SUB_PROCESS_CALL_ACTIVITY);

        processRuntime.start(ProcessPayloadBuilder
            .start()
            .withProcessDefinitionKey(PARENT_PROCESS_CALL_ACTIVITY)
            .build()
        );

        //when
        List<ProcessStartedEvent> processStartedEvents = localEventSource.getEvents(ProcessStartedEvent.class);

        //then
        assertThat(processStartedEvents)
            .extracting(
                event -> event.getEntity().getProcessDefinitionKey(),
                event -> event.getEntity().getProcessDefinitionId(),
                event -> event.getEntity().getProcessDefinitionName(),
                event -> event.getEntity().getProcessDefinitionVersion())
            .containsExactly(
                tuple(
                    parentProcessDefinition.getKey(),
                    parentProcessDefinition.getId(),
                    parentProcessDefinition.getName(),
                    parentProcessDefinition.getVersion()),
                tuple(
                    childProcessDefinition.getKey(),
                    childProcessDefinition.getId(),
                    childProcessDefinition.getName(),
                    childProcessDefinition.getVersion()));
    }
```

You can add it to [ProcessRuntimeEventsIT](https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeEventsIT.java).

Would you mind creating the PR in there? Otherwise, I'll do it later on.

**Comment by erdemedeiros** [comment]
Also, if you create a PR, don't forget to sign the [license CLA](https://cla-assistant.io/Activiti/activiti).

**Comment by erdemedeiros** [comment]
Related to https://github.com/Activiti/Activiti/issues/3506.

**Comment by knowings** [comment]
Hi @erdemedeiros, I'll do the refactor as you suggest as we have also forked this project 😄 

Thank you for the diagnostic.

**Comment by erdemedeiros** [comment]
Thank you!

**Pull request closed without merging**
