### PR TITLE
AAE-12770 add markdown formatting

### PR DESCRIPTION
**Pull request by atchertchian**

### CODE REVIEW

**Review by gicappa — APPROVED** [review]
LGTM!

**Review by erdemedeiros — APPROVED** [review]
LGTM!

**Comment by atchertchian** [comment]
Codacy gives warnings on the markdown format: maybe we can check that @ryewilson please?

**Comment by atchertchian** [comment]
Disregarding Codacy check for this change: not sure about the correctness of `[list-item-indent] Incorrect list-item indent: add 2 spaces` on markdown files, let's assume that might be a bug

**Pull request merged**
