### PR TITLE
Activiti/Activiti#3765 Add category field to Cloud Process Definition

### PR DESCRIPTION
**Pull request by miguelruizdev**
Ref: Activiti/Activiti#3765

### CODE REVIEW

**Comment by miguelruizdev** [comment]
Propagation from Activiti core was cherry-picked in this PR: https://github.com/Activiti/activiti-cloud/pull/531

**Review by jesty — APPROVED** [review]
LGTM

**Review by erdemedeiros — CHANGES_REQUESTED** [review]
Please, also update [QueryProcessDefinitionIT](https://github.com/Activiti/activiti-cloud/blob/develop/activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessDefinitionIT.java) to make sure query service is storing the category properly. LGTM otherwise.

**Comment by miguelruizdev** [comment]
@erdemedeiros checks have been added to `QueryProcessDefinitionIT`: https://github.com/Activiti/activiti-cloud/pull/532/files#diff-6e6b3d4c5150f4cff4ec05eb4fb974034e7e5ee935d417276949f9404e729243R93-R120

**Review by erdemedeiros — APPROVED** [review]
LGTM!

**Pull request merged**
