### PR TITLE
Standardise Event Model: add capability to store json schemas in connector features

### PR DESCRIPTION
**Pull request by rbarroso**

### CODE REVIEW

**Review by pmartinezga — COMMENTED** [review]
I was wondering if there is any chance of validating that the JSON schema is valid on the java side, have you investigated it?

**Review by pmartinezga — APPROVED** [review]
Forget my previous comment, maybe we use no valid JSON schemas in content model events as we will be extending cloud events as reference and the reference will not be present in the JSON schema.

So, all good for me!

**Review by erdemedeiros — APPROVED** [review]
LGTM!

**Comment by erdemedeiros** [comment]
Ref https://github.com/Activiti/Activiti/issues/3670.

**Pull request merged**
